406 feature add sqlx support to interact with the postgres db
dcapal/dcapal pull request #407
Opened 2024-07-31 12:03 UTC by mattiapitossi

Closes #406

2024-08-06 21:18 UTC, leonardoarcari requested changes

2024-08-06 21:18 UTC, leonardoarcari commented on dcapal-backend/docker-compose.yml
> +      - ./volumes/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
This mounted file seems to fail when initializing the container. Check out the `e2e` CI job

2024-08-06 21:18 UTC, leonardoarcari commented on dcapal-backend/src/lib.rs
> +        sqlx::migrate!().run(&postgres).await?;
Think we should migrate the DB outside of DcaPal server app to have better control over it. Something like a job that runs after Postgres container is healthy. Then we make DcaPal container depend on it so we don't start until DB has been migrated.

Something like this but waiting for Postgres healthiness before we run it: https://stackoverflow.com/a/64153124

2024-08-12 07:37 UTC, mattiapitossi commented on dcapal-backend/src/lib.rs
> +        sqlx::migrate!().run(&postgres).await?;
It's a good point. At the moment, the Postgres docker instance is for test and local development purposes only, as we are using the AWS Supabase instance which should be always up and running. I've added a TODO for when we switch to the docker container to run the migration from the script. Let me know if it makes sense for you

2024-08-12 09:09 UTC, mattiapitossi commented on dcapal-backend/docker-compose.yml
> +      - ./volumes/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
The pipeline is now fixed. I've replaced the Supabase docker configuration with plain Postgres so we don't have to rely upon them in the future if we decide to migrate.

2024-08-24 17:07 UTC, leonardoarcari requested changes

2024-08-24 17:07 UTC, leonardoarcari commented on dcapal-backend/docker-compose.yml
> +      - postgres_data:/var/lib/postgresql/data
For consistency with the other containers

```suggestion
      - ./data/postgres:/var/lib/postgresql/data
```

2024-08-24 17:07 UTC, leonardoarcari commented on dcapal-backend/docker-compose.yml
> +      - ./docker/scripts:/docker-entrypoint-initdb.d
Please move `docker/scripts` under `config/postgres/scripts` and mount that folder
```suggestion
      - ./config/docker/scripts:/docker-entrypoint-initdb.d
```

2024-08-24 17:07 UTC, leonardoarcari commented on dcapal-backend/.gitignore
> +volumes/**
Is this still needed?

2024-08-24 17:27 UTC, leonardoarcari commented on dcapal-backend/src/lib.rs
> +        sqlx::migrate!().run(&postgres).await?;
Yeah I agree for the healthcheck part 👍 But for the migration part, imo it's an anti-pattern to run it as part of the main application.

When you make any DB change, I find it less error prone to run the `sqlx migrate` step against the AWS instance, verify it's all good and then deploy the new image.

Given how small time we have to maintain the app, I don't want to risk unintentional migrations happening across restarts.

Do you mind adding a migrate script similar to the `start.sh` you provided? `sqlx` should be smart enough to pick up any `.env` file in the same folder and use the Postgres connection params to connect to the AWS/local instance.

2024-08-24 17:30 UTC, leonardoarcari commented on dcapal-backend/docker-compose.yml
> +      - ./volumes/db/webhooks.sql:/docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql:Z
Awesome! 🙌

2024-09-04 09:19 UTC, mattiapitossi commented
Closing as these features will be added in #431

2024-09-04 09:19 UTC, closed without merging